using Microsoft.EntityFrameworkCore;
using New_folder.Data;
using New_folder.Services;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddRazorPages();
builder.Services.AddDbContext<BookContext>(options =>
    options.UseNpgsql(builder.Configuration.GetConnectionString("DefaultConnection")));
builder.Services.AddScoped<IBookService, BookService>();

var app = builder.Build();

using (var scope = app.Services.CreateScope())
{
    var context = scope.ServiceProvider.GetRequiredService<BookContext>();
    try
    {
        context.Database.ExecuteSqlRaw("DROP TABLE IF EXISTS \"__EFMigrationsHistory\" CASCADE;");
        context.Database.ExecuteSqlRaw("DROP TABLE IF EXISTS \"Books\" CASCADE;");
    }
    catch { }
    
    context.Database.ExecuteSqlRaw($@"
        CREATE TABLE ""Books"" (
            ""Id"" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            ""Title"" TEXT NOT NULL,
            ""Author"" TEXT NOT NULL,
            ""Year"" INTEGER NOT NULL,
            ""Description"" TEXT
        );
    ");
}

if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    app.UseHsts();
}

app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

app.UseAuthorization();

app.MapRazorPages();

app.Run();
